#----------------------------------------------------------------------
# This file was generated by C:\Python27\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

catalog = {}
index = []

Icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAABB6QAAQekBx7aNcQAAAAd0SU1FB9sMAgIZCTqMphQAAAcn"
    "SURBVFjDnZdfjFRXHcc/v3PuvTOzs7PLn86yEOMqi1sqq1uopAbRYCzGQpA+mGg3UIVi2uiD"
    "jQnIm+BDI03aBEmNaU0wqWmMobz2AWOqwRehlELaELbILkaWxY0L8//+Oef4cGeGmV12aXuS"
    "ydxz7j2/8/v9vt/fnyOPb95scQ4ARNL/TzFvriAiSGsdsNZijAFAa33vnXMggueam1pCP+m8"
    "tdYaSZIQxzHWWpRS5PN5li9fjjGGWr1OEsepos3vPWkJEEGaLz7OvGWJMYa4JVSEgYEBRkdH"
    "yeZy3L17l7t37lAqlahWq3QO15TndWrjms9LzXEOEcFaS7VSwfN91qxZw9jYGI9u3Mjc3Bzv"
    "X7zI1NQUiTFUymVKpRLW2m4ImvK8TkxlHsZyH4y11kRRRKVcZuThh9mxcyejo6NcuXKFt06d"
    "Yub2baqVCnEco5VCaY3neXieh2vB1iH/wRxoWizN51KpRF9fHz974QW+sW0bH37wAS8dO8bk"
    "5GTbQs/z8H0/PbC5t+W5+fIfyIHWiKKISqXCli1bOHT4MAKcOHGCM2fOkO/pIZfrQZkQEYdR"
    "qg0fD5Cv6MC5HUodm5VSNBoNarUa+/fv53evvcb169c58Oyz/O2dd3ho5UpyuR60adDo+wz1"
    "/Gp00ugi3GLyF+VACyulFEmSICL88sgRnh4f57evvsqJ48fxfJ9CoYAFVNIgzvRzdfPPEZuw"
    "4ewRVNLA6gBx9p4i9+GYcp0JpYMDIkK9XscYw5GjR3l6fJyXjh3jlZdfJpPNks/n02+tQYAb"
    "XxyntnID1eIY/37k+4gziLM4Edw8+Z3nqZYr3DztwjAkDEMOHTrE7qee4jfHj/OHkyfp7+sj"
    "m822D9dxjZnPfZvba5+EqAJJjel13+W/Q99Ex9W2B1ry55+3gAPtGK9W2X/gAD8YH+f06dP8"
    "/vXXKRQK+EGQRoZz+FGZUvFLTI4+AyjEGbAJKJ/J0X2UV67HD0tIR4TNP0+1rW7+lFLUqlWe"
    "2L6dgwcPcvXqVX794ospXkq1c7gyDeqFNXy06afYniKYsGmVQNIg6V3NtY0/oZEfQJkwPbgz"
    "DziXRkEbkybutVqNVYOD/OLwYQB+dfQopVKJXC6HtSmmyiY48Zga/RGNFesh6k6zAMRVasUv"
    "c2PDXkAQa1I+LMaBViGx1jK+Zw9DQ0P88Y03ePf8eXp7e7uqn07qTK/bxezQtyCpgzMdgdt0"
    "sjWQ1Ln9+e9wa+2TeHG1i4gLOOCco1qtsn79evbt20e5XOatU6dQSqVptOlCLywxu/pxph4Z"
    "T/E20b3D3bzoNxE4x+SGPcytegwvLLdh6OZA0/ogCNizdy9KKf705ptMTEyQy+Xa+OmkRm35"
    "MDc2PQ+5PpSLUQqUcum/0Jx3rLkI17OSqU3PUe//LCqpI7iUyIDXSjpxHLN2eJhdu3cThiFn"
    "z57FOYfnpbkKE5PoHHMbnyFTHKInLEFwL2mlHrI4UV31PvV0CTM4wtyje1j1j1fAxIhOo8lr"
    "cyaO2bFzJwKcO3eOy5cvUygUUuHWIklI9JXvEaz7KgPxHfBNt8cRnLXNHC8grisVwxxuZCvh"
    "nQkyF/+MUx4iCk9EMMbQ29vLtm3bAHjvwgUqlQrFYpHEWFxYQb7wdTJjO8hQARWD6obcAVjX"
    "pPUCSgIxKAubdsHdKdy//onk+lIFwjDka1u3MjIyQqPR4N3z58lms1hrwMRk1z5G4Ykfo/qW"
    "Q9TASabLahs1cNbglENEAQ7RGuXnkI44E4C+Aez25yi/XSe8NYGnlKJerzM2NgbAzMwMExMT"
    "BEGANRZRGr/vIeQ/lzHXyt11w1rEC+hZsw7dswxr0sIlWpOUZ2ncuoZNYkR18MI5JFvA6y8S"
    "zlzDs9aSzWYZHh4G4Nb0NHNzcxQKhXb1qnz4d8rv/6Xbr4CNQvzCCgo7n6ewbBmmEYEodOBR"
    "mpvif389SVIrofyge6MD8TOI9vDiOGZwcJDB1asBuHnzZppy23XJIdpHvGBBsnM6QGfz5LQj"
    "T0SiEgRBo4k16GwvxtqFCrTaPOdSBYrFIgMDAwDMzs521O+m41q1Yl7FdM6Cs+SI6ZWIWCIA"
    "fIQ6MTibfmvtfe8VIoJnkoS+/n5WrFgBQKPRmO+tJXpGQXAEJGSJ0KRZMRBNQAK4e7l/kZ7T"
    "s84RBEHXxaKzdV6qZ2wN3yVkiFCuqYBT+CQfqyf08vk8ly9d4od79yIizM7OttPvx7onAB4x"
    "gY3AxQgQOIV2SduEpfZ7nudRKpWYnp4G58jlcmSy2QWEuV9PB4I4h0pCdFJHJyEgKO2aPYDj"
    "QfcOzzqH7/ss6++HVr3uuDwuyQHnEIGejKaQ84hUWpaDjEePr7vhWowDn/ZuiAja84jjmEvv"
    "XeDaxFWsMWm3pDWVUgljDFrrpTnwSe+GnXNRCmMMH01MYK3tQk0phe/77ZyymLz/A/2PnsoI"
    "fHfRAAAAAElFTkSuQmCC")
index.append('Icon')
catalog['Icon'] = Icon
getIconData = Icon.GetData
getIconImage = Icon.GetImage
getIconBitmap = Icon.GetBitmap
getIconIcon = Icon.GetIcon

